language: python
python:
- '3.7'
install:
- make dev_env
env:
  global:
  - PYTHONPATH=/home/travis/build/fdnthecoder/Orion
  - ORION_HOME=/home/travis/build/fdnthecoder/Orion
script:
- make tests
deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: sd-orion-api
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL