---
language: python

python:
    - '3.7'

install:
    - make dev_env

env:
    global:
        - PYTHONPATH=/home/travis/build/fdnthecoder/Orion
        - GAME_HOME=/home/travis/build/fdnthecoder/Orion

script:
    - make tests

# deploy to heroku
deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: orion-api
